name: check.yml
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: pcov
          tools: composer

      - name: install dependencies
        run: make install

      - name: create database
        run: touch database/database.sqlite

      - name: Install Breeze frontend
        run: |
          php artisan breeze:install blade
          sed -i "s/import '.\/bootstrap';//" resources/js/app.js
          npm install
          npm run build

      - name: migrations
        run: make init

      - name: fix coding standards
        run: make lint-r
      - name: linter
        run: make lint

      - name: tests
        run: make test

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}
